site_name: Chin's Blog
theme:
  name: material
  language: zh
  hljs_languages:
    - yaml
markdown_extensions:
  - toc:
      permalink: true
  - pymdownx.highlight:
      linenums: true
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.superfences
nav:
  - 主页: index.md
